// Adds strain data directly — no API needed.
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const STRAINS_PATH = path.join(__dirname, "../strains.json");
const existing = JSON.parse(fs.readFileSync(STRAINS_PATH, "utf8"));
const existingNames = new Set(existing.map(s => s.name.toLowerCase()));

const NEW_STRAINS = [
  // ── LANDRACE / HERITAGE ────────────────────────────────────────────────────
  { name:"Thai", type:"sativa", thc_min:14, thc_max:22, cbd:0.1, description:"One of the original landrace sativas from Southeast Asia, Thai delivers a soaring, psychedelic cerebral high that fueled the creative counterculture of the 1970s. Expect a sweet, earthy, and slightly spicy aroma with long-lasting, energetic euphoria.", effects:["Energetic","Creative","Euphoric","Uplifted","Focused"], terpenes:["Terpinolene","Ocimene","Myrcene"], flavors:["Earthy","Sweet","Spicy","Herbal"], tags:["daytime","landrace","sativa-dom","creative","classic"], rating:4.5 },
  { name:"Mexican Sativa", type:"sativa", thc_min:10, thc_max:18, cbd:0.2, description:"A classic landrace from the highlands of Mexico, this strain offers a light, uplifting buzz perfect for social situations and creative endeavors. Its aroma is earthy and herbal with subtle citrus notes.", effects:["Happy","Energetic","Uplifted","Creative","Talkative"], terpenes:["Myrcene","Limonene","Terpinolene"], flavors:["Earthy","Herbal","Citrus","Woody"], tags:["daytime","landrace","sativa-dom","social","classic"], rating:4.2 },
  { name:"Malawi Gold", type:"sativa", thc_min:14, thc_max:20, cbd:0.1, description:"Hailing from the Malawi region of Africa, this legendary landrace is prized for its long, golden buds and soaring sativa effects. The high is euphoric, clear-headed, and lasting — great for deep focus or artistic flow.", effects:["Energetic","Euphoric","Creative","Focused","Uplifted"], terpenes:["Terpinolene","Limonene","Pinene"], flavors:["Sweet","Earthy","Fruity","Woody"], tags:["daytime","landrace","sativa-dom","creative","rare"], rating:4.4 },
  { name:"Swazi Gold", type:"sativa", thc_min:12, thc_max:18, cbd:0.1, description:"A golden sativa from the mountains of Swaziland in southern Africa. Swazi Gold produces a happy, uplifting high with a gentle, long-lasting energetic buzz. Its flavor profile is earthy, fruity, and subtly sweet.", effects:["Happy","Energetic","Uplifted","Creative","Relaxed"], terpenes:["Myrcene","Terpinolene","Limonene"], flavors:["Earthy","Fruity","Sweet","Herbal"], tags:["daytime","landrace","sativa-dom","classic","rare"], rating:4.2 },
  { name:"Nepalese", type:"sativa", thc_min:13, thc_max:19, cbd:0.2, description:"A Himalayan landrace from Nepal, this strain is one of the most revered in the world of hash-making. Its effect is cerebral and uplifting with a dreamy, floaty quality. Aroma is earthy, floral, and slightly spicy.", effects:["Uplifted","Happy","Creative","Euphoric","Relaxed"], terpenes:["Myrcene","Pinene","Linalool"], flavors:["Earthy","Floral","Spicy","Herbal"], tags:["daytime","landrace","hash","classic","rare"], rating:4.3 },
  { name:"Kilimanjaro", type:"sativa", thc_min:15, thc_max:21, cbd:0.1, description:"An East African landrace from the slopes of Mount Kilimanjaro. This powerful sativa is known for delivering an energetic, euphoric rush with strong cerebral effects and a sweet, fruity aroma.", effects:["Energetic","Euphoric","Creative","Happy","Uplifted"], terpenes:["Terpinolene","Limonene","Ocimene"], flavors:["Sweet","Fruity","Earthy","Tropical"], tags:["daytime","landrace","sativa-dom","rare","creative"], rating:4.3 },

  // ── HAZE FAMILY ──────────────────────────────────────────────────────────────
  { name:"Original Haze", type:"sativa", thc_min:18, thc_max:24, cbd:0.1, description:"The legendary progenitor of virtually every haze variety in existence. Original Haze delivers an intense, psychedelic, long-lasting cerebral high with a complex spicy-earthy-citrus aroma. Not for beginners.", effects:["Energetic","Creative","Euphoric","Uplifted","Focused"], terpenes:["Terpinolene","Myrcene","Ocimene","Caryophyllene"], flavors:["Earthy","Spicy","Citrus","Herbal","Woody"], tags:["daytime","sativa-dom","creative","classic","legendary"], rating:4.7 },
  { name:"Silver Haze", type:"sativa", thc_min:18, thc_max:24, cbd:0.1, description:"A Silver Haze cross that delivers the classic haze experience with a slightly more manageable intensity. Crystal-coated buds produce a sharp, spicy-citrus aroma and an electric, euphoric head high.", effects:["Energetic","Euphoric","Creative","Uplifted","Focused"], terpenes:["Terpinolene","Limonene","Myrcene"], flavors:["Citrus","Spicy","Earthy","Herbal"], tags:["daytime","sativa-dom","creative","award-winning","haze"], rating:4.5 },
  { name:"Blue Haze", type:"hybrid", thc_min:17, thc_max:22, cbd:0.1, description:"A beautiful cross of Blueberry and Haze that tempers the haze's intensity with the indica sweetness of Blueberry. Expect a balanced, blissful euphoria with a sweet berry aroma and a long, pleasant high.", effects:["Happy","Relaxed","Euphoric","Uplifted","Creative"], terpenes:["Myrcene","Terpinolene","Linalool"], flavors:["Berry","Blueberry","Earthy","Sweet","Floral"], tags:["hybrid","daytime","haze","berry","award-winning"], rating:4.4 },
  { name:"Strawberry Haze", type:"sativa", thc_min:17, thc_max:23, cbd:0.1, description:"Strawberry Haze brings together the fruity sweetness of Strawberry Cough with the electric energy of Haze genetics. The result is a vibrant, uplifting strain with a striking sweet-strawberry aroma and a long-lasting head high.", effects:["Energetic","Happy","Uplifted","Creative","Euphoric"], terpenes:["Terpinolene","Limonene","Myrcene"], flavors:["Strawberry","Sweet","Berry","Citrus","Earthy"], tags:["daytime","sativa-dom","fruity","creative","haze"], rating:4.4 },
  { name:"Mango Haze", type:"sativa", thc_min:16, thc_max:22, cbd:0.1, description:"A tropical take on classic Haze genetics, Mango Haze smells exactly as its name suggests — ripe mango with spicy haze undertones. Its effect is energetic and euphoric, perfect for a productive or creative day.", effects:["Energetic","Creative","Happy","Uplifted","Euphoric"], terpenes:["Terpinolene","Myrcene","Ocimene"], flavors:["Mango","Tropical","Sweet","Earthy","Spicy"], tags:["daytime","sativa-dom","fruity","creative","tropical"], rating:4.4 },
  { name:"Shiva Haze", type:"sativa", thc_min:18, thc_max:24, cbd:0.1, description:"Named after the Hindu deity of transformation, Shiva Haze delivers a mind-bending, uplifting cerebral experience. This potent sativa is not for the faint of heart — it hits fast with euphoric energy and a complex herbal, citrus aroma.", effects:["Euphoric","Energetic","Creative","Uplifted","Focused"], terpenes:["Terpinolene","Pinene","Limonene"], flavors:["Earthy","Herbal","Citrus","Spicy","Pine"], tags:["daytime","sativa-dom","potent","creative","haze"], rating:4.5 },
  { name:"Amnesia", type:"sativa", thc_min:20, thc_max:25, cbd:0.1, description:"A legendary Amsterdam coffee shop staple, Amnesia hits hard with an intensely euphoric, psychedelic rush that can overwhelm inexperienced users. Its complex aroma blends earthy, lemony, and spicy notes into something truly unforgettable.", effects:["Euphoric","Energetic","Creative","Uplifted","Happy"], terpenes:["Terpinolene","Myrcene","Limonene"], flavors:["Lemony","Earthy","Spicy","Citrus","Herbal"], tags:["daytime","sativa-dom","potent","creative","legendary"], rating:4.7 },
  { name:"Pineapple Haze", type:"sativa", thc_min:17, thc_max:23, cbd:0.1, description:"Pineapple Haze merges the tropical sweetness of Pineapple with the cerebral energy of Haze. The result is a bright, happy, and motivating strain with a juicy pineapple-citrus aroma that brightens any mood.", effects:["Happy","Energetic","Uplifted","Creative","Euphoric"], terpenes:["Terpinolene","Limonene","Ocimene"], flavors:["Pineapple","Tropical","Citrus","Sweet","Earthy"], tags:["daytime","sativa-dom","fruity","creative","tropical"], rating:4.3 },
  { name:"G13 Haze", type:"hybrid", thc_min:20, thc_max:26, cbd:0.1, description:"The legendary G13 government indica crossed with a Haze sativa creates a powerful hybrid with the best of both worlds. Expect heavy, stoney body relaxation wrapped in a euphoric, cerebral buzz, backed by a complex earthy-spicy aroma.", effects:["Euphoric","Relaxed","Happy","Creative","Uplifted"], terpenes:["Myrcene","Terpinolene","Caryophyllene"], flavors:["Earthy","Spicy","Herbal","Pine","Citrus"], tags:["hybrid","potent","creative","legendary","medical"], rating:4.6 },
  { name:"Grapefruit Haze", type:"sativa", thc_min:17, thc_max:22, cbd:0.1, description:"A bright, citrusy sativa that blends Grapefruit's tangy sweetness with Haze's electric energy. The aroma is unmistakably citrus-forward with a sharp grapefruit bite and an effect that's uplifting, social, and mood-boosting.", effects:["Happy","Energetic","Uplifted","Euphoric","Creative"], terpenes:["Limonene","Terpinolene","Myrcene"], flavors:["Grapefruit","Citrus","Sweet","Earthy","Tangy"], tags:["daytime","sativa-dom","citrus","social","creative"], rating:4.3 },

  // ── KUSH / OG VARIANTS ──────────────────────────────────────────────────────
  { name:"Ghost OG", type:"hybrid", thc_min:20, thc_max:28, cbd:0.1, description:"Ghost OG is one of the most celebrated OG cuts, prized for its exceptional resin production and intense citrus-pine aroma. The high is powerfully euphoric and relaxing, melting away stress and pain while keeping the mind clear enough to function.", effects:["Euphoric","Relaxed","Happy","Uplifted","Creative"], terpenes:["Myrcene","Limonene","Caryophyllene"], flavors:["Citrus","Pine","Earthy","Lemon","Woody"], tags:["hybrid","evening","potent","og","medical"], rating:4.7 },
  { name:"Lemon OG Kush", type:"hybrid", thc_min:18, thc_max:24, cbd:0.1, description:"Lemon OG brings a bright citrus twist to classic OG Kush genetics. Sharp lemon zest over earthy, piney OG base notes create a distinctive aroma. The effect is a relaxed but uplifting experience, ideal for stress relief with mental clarity.", effects:["Relaxed","Happy","Euphoric","Uplifted","Sleepy"], terpenes:["Limonene","Myrcene","Caryophyllene"], flavors:["Lemon","Citrus","Earthy","Pine","Sweet"], tags:["evening","hybrid","citrus","stress-relief","og"], rating:4.5 },
  { name:"Diablo OG", type:"hybrid", thc_min:20, thc_max:26, cbd:0.1, description:"Diablo OG is a potent, fast-hitting OG cross that delivers a heavy, sedating body effect paired with a deep, euphoric head high. Its aroma is pungently earthy and piney with diesel undertones — classic OG character turned up to 11.", effects:["Relaxed","Euphoric","Sleepy","Happy","Sedated"], terpenes:["Myrcene","Caryophyllene","Limonene"], flavors:["Earthy","Pine","Diesel","Woody","Citrus"], tags:["nighttime","indica-dom","potent","og","medical"], rating:4.5 },
  { name:"Obama Kush", type:"indica", thc_min:16, thc_max:22, cbd:0.2, description:"Obama Kush is a deeply relaxing indica with a smooth, sweet flavor profile and mellow, stress-melting effects. Named for its presidential-grade quality, it delivers full body calm and gentle euphoria — perfect for unwinding after a long day.", effects:["Relaxed","Happy","Euphoric","Sleepy","Uplifted"], terpenes:["Myrcene","Caryophyllene","Linalool"], flavors:["Earthy","Sweet","Floral","Berry","Herbal"], tags:["nighttime","indica-dom","relaxing","medical","stress-relief"], rating:4.3 },
  { name:"Presidential OG", type:"indica", thc_min:20, thc_max:26, cbd:0.1, description:"Presidential OG lives up to its name with a powerful, full-body sedation and a supremely relaxing effect. This is a heavy indica best reserved for evening use. Its aroma is rich, earthy, and piney with a smooth, almost creamy smoke.", effects:["Relaxed","Sleepy","Euphoric","Happy","Sedated"], terpenes:["Myrcene","Linalool","Caryophyllene"], flavors:["Earthy","Pine","Woody","Herbal","Sweet"], tags:["nighttime","indica-dom","potent","sedating","medical"], rating:4.4 },
  { name:"Lemon Kush", type:"hybrid", thc_min:17, thc_max:22, cbd:0.2, description:"Lemon Kush delivers a perfect balance of kush relaxation and bright citrus energy. The lemon aroma is sharp and clean, while the effect is gently euphoric and body-relaxing without putting you to sleep. Great for daytime stress relief.", effects:["Happy","Relaxed","Uplifted","Euphoric","Creative"], terpenes:["Limonene","Myrcene","Caryophyllene"], flavors:["Lemon","Citrus","Earthy","Sweet","Pine"], tags:["daytime","hybrid","citrus","stress-relief","beginner-friendly"], rating:4.3 },
  { name:"Kandy Kush", type:"indica", thc_min:18, thc_max:24, cbd:0.1, description:"Kandy Kush is a cross of OG Kush and Trainwreck, delivering a sweet, candy-like aroma with potent indica relaxation. The high is deeply physical and euphoric, easing tension and melting into pleasant sleepiness.", effects:["Relaxed","Euphoric","Happy","Sleepy","Sedated"], terpenes:["Myrcene","Caryophyllene","Linalool"], flavors:["Sweet","Candy","Earthy","Pine","Citrus"], tags:["nighttime","indica-dom","relaxing","sweet","medical"], rating:4.3 },
  { name:"Candy Kush", type:"hybrid", thc_min:16, thc_max:21, cbd:0.1, description:"A sweet, dessert-like hybrid that combines the relaxing qualities of kush genetics with a candy-sweet flavor that's hard to resist. Candy Kush offers a gentle, happy buzz perfect for social settings or winding down.", effects:["Happy","Relaxed","Uplifted","Euphoric","Giggly"], terpenes:["Myrcene","Limonene","Linalool"], flavors:["Sweet","Candy","Fruity","Earthy","Floral"], tags:["evening","hybrid","sweet","social","beginner-friendly"], rating:4.2 },
  { name:"Hash Plant", type:"indica", thc_min:17, thc_max:22, cbd:0.2, description:"A classic indica bred specifically for resin production and hash-making. Hash Plant delivers a deeply sedating, heavy body high with an intensely earthy, dank, and almost hashy aroma. This is a couch-lock indica through and through.", effects:["Relaxed","Sleepy","Sedated","Happy","Euphoric"], terpenes:["Myrcene","Caryophyllene","Pinene"], flavors:["Earthy","Dank","Woody","Herbal","Hash"], tags:["nighttime","indica-dom","sedating","hash","classic"], rating:4.4 },
  { name:"Grape Kush", type:"indica", thc_min:17, thc_max:22, cbd:0.1, description:"Grape Kush is a fragrant indica with a deep, sweet grape aroma that carries into a smooth, berry-sweet smoke. The effect is classic indica — full-body relaxation and a calm, euphoric mood. Great for evening pain or insomnia relief.", effects:["Relaxed","Happy","Euphoric","Sleepy","Sedated"], terpenes:["Myrcene","Linalool","Caryophyllene"], flavors:["Grape","Berry","Sweet","Earthy","Floral"], tags:["nighttime","indica-dom","fruity","medical","relaxing"], rating:4.3 },
  { name:"Strawberry Kush", type:"hybrid", thc_min:17, thc_max:22, cbd:0.1, description:"Strawberry Kush combines the sweetness of Strawberry Cough with the heavy relaxation of OG Kush. The result is a pleasantly aromatic hybrid with a strawberry-sweet flavor and balanced effect — uplifting at first, then drifting into mellow relaxation.", effects:["Happy","Relaxed","Euphoric","Uplifted","Sleepy"], terpenes:["Myrcene","Limonene","Linalool"], flavors:["Strawberry","Sweet","Berry","Earthy","Citrus"], tags:["evening","hybrid","fruity","relaxing","beginner-friendly"], rating:4.3 },
  { name:"Blueberry Kush", type:"indica", thc_min:17, thc_max:22, cbd:0.1, description:"Blueberry Kush is a sweet, aromatic indica cross of Blueberry and OG Kush. Its deep blueberry aroma and smooth berry flavor make it one of the more enjoyable pure indicas. The effect is deeply relaxing with a happy, euphoric undertone.", effects:["Relaxed","Happy","Sleepy","Euphoric","Sedated"], terpenes:["Myrcene","Linalool","Caryophyllene"], flavors:["Blueberry","Berry","Sweet","Earthy","Fruity"], tags:["nighttime","indica-dom","fruity","medical","relaxing"], rating:4.4 },
  { name:"Cotton Candy Kush", type:"hybrid", thc_min:16, thc_max:21, cbd:0.1, description:"Cotton Candy Kush is a playfully sweet hybrid with an aroma reminiscent of, well, cotton candy. Its effect is light and euphoric with gentle body relaxation — an easygoing, fun strain that's great for social occasions.", effects:["Happy","Uplifted","Relaxed","Giggly","Euphoric"], terpenes:["Myrcene","Limonene","Linalool"], flavors:["Sweet","Candy","Floral","Berry","Vanilla"], tags:["daytime","hybrid","sweet","social","beginner-friendly"], rating:4.2 },

  // ── DIESEL VARIANTS ──────────────────────────────────────────────────────────
  { name:"East Coast Sour Diesel", type:"sativa", thc_min:19, thc_max:25, cbd:0.1, description:"The original East Coast Sour D is the gold standard diesel sativa — fuel, citrus, and chemical aromas explode from the bag before you even open it. The effect is famously euphoric, energizing, and cerebral, beloved by creatives and professionals alike.", effects:["Energetic","Euphoric","Creative","Focused","Uplifted"], terpenes:["Terpinolene","Limonene","Myrcene","Caryophyllene"], flavors:["Diesel","Citrus","Earthy","Chemical","Lemon"], tags:["daytime","sativa-dom","potent","classic","creative"], rating:4.8 },
  { name:"Strawberry Diesel", type:"hybrid", thc_min:18, thc_max:23, cbd:0.1, description:"Strawberry Diesel bridges the gap between fruity and fuel, combining the sweet strawberry aromas of Strawberry Cough with the energetic rush of Sour Diesel. A perfectly balanced hybrid that tastes great and hits even better.", effects:["Energetic","Happy","Uplifted","Creative","Euphoric"], terpenes:["Terpinolene","Limonene","Myrcene"], flavors:["Strawberry","Diesel","Sweet","Berry","Citrus"], tags:["daytime","hybrid","fruity","creative","social"], rating:4.4 },
  { name:"Lemon Diesel", type:"hybrid", thc_min:17, thc_max:22, cbd:0.1, description:"Lemon Diesel takes diesel genetics and drenches them in citrus. The result is a sharp, lemony strain with serious fuel undertones and a clear-headed, energizing effect that's great for daytime productivity.", effects:["Energetic","Focused","Happy","Uplifted","Creative"], terpenes:["Limonene","Terpinolene","Myrcene"], flavors:["Lemon","Diesel","Citrus","Earthy","Sour"], tags:["daytime","hybrid","citrus","focus","creative"], rating:4.3 },
  { name:"Blue Diesel", type:"hybrid", thc_min:17, thc_max:22, cbd:0.1, description:"Blue Diesel blends the sweet blueberry notes of Blueberry with the fuel punch of NYC Diesel. The result is a well-balanced hybrid with a pleasant, sweet-diesel aroma and an easy, happy buzz that's not too overpowering.", effects:["Happy","Relaxed","Uplifted","Euphoric","Creative"], terpenes:["Myrcene","Limonene","Linalool"], flavors:["Blueberry","Diesel","Sweet","Berry","Earthy"], tags:["daytime","hybrid","fruity","social","beginner-friendly"], rating:4.3 },
  { name:"Banana Diesel", type:"hybrid", thc_min:19, thc_max:24, cbd:0.1, description:"Banana Diesel is a head-turning combination of tropical banana sweetness and the sharp, energizing kick of diesel. The nose is remarkably fruity with a fuel accent, and the effect is uplifting and euphoric with relaxing body notes.", effects:["Happy","Uplifted","Euphoric","Relaxed","Creative"], terpenes:["Myrcene","Limonene","Terpinolene"], flavors:["Banana","Diesel","Tropical","Sweet","Earthy"], tags:["hybrid","daytime","fruity","creative","social"], rating:4.3 },
  { name:"Headband OG", type:"hybrid", thc_min:20, thc_max:27, cbd:0.1, description:"Headband OG gets its name from the characteristic pressure users feel around their forehead and temples — a telltale sign of its potency. A cross of OG Kush and Sour Diesel, it delivers a slow-building, creeping euphoria with heavy relaxation.", effects:["Euphoric","Relaxed","Happy","Creative","Uplifted"], terpenes:["Myrcene","Limonene","Caryophyllene"], flavors:["Diesel","Earthy","Lemon","Pine","Citrus"], tags:["hybrid","potent","evening","og","creative"], rating:4.5 },

  // ── CHEESE FAMILY ────────────────────────────────────────────────────────────
  { name:"Original Cheese", type:"hybrid", thc_min:15, thc_max:20, cbd:0.1, description:"The original Cheese clone from the UK that started a global movement. Its unmistakable pungent, sharp cheese aroma is unlike anything else in cannabis. The effect is uplifting and euphoric with a solid indica relaxation — a true classic.", effects:["Happy","Relaxed","Euphoric","Uplifted","Hungry"], terpenes:["Myrcene","Caryophyllene","Limonene"], flavors:["Cheese","Earthy","Pungent","Savory","Herbal"], tags:["hybrid","classic","uk","pungent","beginner-friendly"], rating:4.6 },
  { name:"Big Buddha Cheese", type:"hybrid", thc_min:15, thc_max:20, cbd:0.1, description:"Big Buddha Cheese is an award-winning phenotype of Cheese that has won multiple Cannabis Cups. It retains the sharp cheese aroma but adds a sweeter edge and a more balanced effect — euphoric, happy, and relaxing without being sedating.", effects:["Happy","Euphoric","Relaxed","Uplifted","Giggly"], terpenes:["Myrcene","Caryophyllene","Linalool"], flavors:["Cheese","Sweet","Earthy","Herbal","Pungent"], tags:["hybrid","award-winning","classic","uk","social"], rating:4.5 },
  { name:"Exodus Cheese", type:"hybrid", thc_min:16, thc_max:20, cbd:0.1, description:"Exodus Cheese is the legendary original Skunk #1 phenotype that evolved into what the UK calls 'Cheese.' Its uniquely funky, skunky-cheese aroma is a cannabis cultural touchstone. The effect is happy, uplifting, and enduringly popular.", effects:["Happy","Relaxed","Euphoric","Uplifted","Creative"], terpenes:["Myrcene","Caryophyllene","Limonene"], flavors:["Cheese","Skunk","Earthy","Pungent","Herbal"], tags:["hybrid","classic","uk","legendary","social"], rating:4.6 },
  { name:"Cheese Quake", type:"hybrid", thc_min:17, thc_max:22, cbd:0.1, description:"Cheese Quake is a cross of Cheese and Querkle that delivers a funky, berry-grape aroma over the classic Cheese base. The effect is a euphoric, relaxing hybrid that hits both body and mind with equal force.", effects:["Relaxed","Euphoric","Happy","Uplifted","Sleepy"], terpenes:["Myrcene","Caryophyllene","Linalool"], flavors:["Cheese","Grape","Berry","Earthy","Pungent"], tags:["hybrid","evening","pungent","fruity","relaxing"], rating:4.3 },

  // ── COOKIES / DESSERT ────────────────────────────────────────────────────────
  { name:"Thin Mint GSC", type:"hybrid", thc_min:19, thc_max:26, cbd:0.1, description:"The Thin Mint cut of Girl Scout Cookies is arguably the most coveted phenotype — its cool, minty undertones layered over the classic GSC sweetness are unforgettable. Dense, resin-drenched buds deliver a euphoric, body-heavy high.", effects:["Euphoric","Relaxed","Happy","Uplifted","Creative"], terpenes:["Caryophyllene","Limonene","Linalool"], flavors:["Mint","Sweet","Earthy","Cookie","Spicy"], tags:["hybrid","potent","evening","cookie","dessert"], rating:4.7 },
  { name:"Animal Mints", type:"hybrid", thc_min:22, thc_max:30, cbd:0.1, description:"Animal Mints is an extraordinarily potent cross of Animal Cookies and SinMint Cookies. Its minty, fuel-like aroma is distinctive and the effect is intensely euphoric and physically heavy — not for beginners. One of the most terpene-rich modern hybrids.", effects:["Euphoric","Relaxed","Sedated","Happy","Creative"], terpenes:["Caryophyllene","Limonene","Myrcene"], flavors:["Mint","Sweet","Earthy","Fuel","Cookie"], tags:["nighttime","potent","hybrid","dessert","modern"], rating:4.7 },
  { name:"Wookies", type:"hybrid", thc_min:21, thc_max:28, cbd:0.1, description:"Wookies is a cross of Girl Scout Cookies, White 91, and The White — a resin monster with a complex, sweet-earthy aroma and an intensely euphoric, body-relaxing high. Covered in so many trichomes it almost looks white.", effects:["Euphoric","Relaxed","Happy","Creative","Uplifted"], terpenes:["Caryophyllene","Myrcene","Limonene"], flavors:["Sweet","Earthy","Cookie","Vanilla","Spicy"], tags:["hybrid","potent","evening","dessert","modern"], rating:4.6 },
  { name:"Pink Cookies", type:"hybrid", thc_min:19, thc_max:25, cbd:0.1, description:"Also known as Wedding Cake, Pink Cookies is a cross of Triangle Kush and Animal Mints that delivers a rich, vanilla-sweet aroma and a powerful, balanced high. Euphoric and relaxing with a dessert-like flavor profile.", effects:["Relaxed","Euphoric","Happy","Uplifted","Sleepy"], terpenes:["Caryophyllene","Limonene","Myrcene"], flavors:["Sweet","Vanilla","Cookie","Earthy","Tangy"], tags:["hybrid","evening","dessert","potent","award-winning"], rating:4.6 },
  { name:"Sunset Cookies", type:"hybrid", thc_min:18, thc_max:24, cbd:0.1, description:"Sunset Cookies is a warm, dessert-forward hybrid with sweet orange and vanilla notes over a cookie base. The effect is a happy, mellow euphoria that winds into gentle body relaxation — ideal for evenings.", effects:["Happy","Relaxed","Euphoric","Uplifted","Sleepy"], terpenes:["Limonene","Caryophyllene","Linalool"], flavors:["Orange","Sweet","Cookie","Vanilla","Earthy"], tags:["evening","hybrid","dessert","sweet","relaxing"], rating:4.4 },
  { name:"Georgia Pie", type:"hybrid", thc_min:20, thc_max:28, cbd:0.1, description:"Georgia Pie is a Seed Junky cross of Gelatti and Kush Mints that smells like a fresh Georgia peach with undertones of cream and earth. The high is fast-acting and euphoric, settling into deep body relaxation. Extremely sought-after in the modern exotic market.", effects:["Euphoric","Relaxed","Happy","Uplifted","Creative"], terpenes:["Caryophyllene","Limonene","Myrcene"], flavors:["Peach","Sweet","Cream","Earthy","Fruity"], tags:["hybrid","exotic","modern","evening","potent"], rating:4.7 },
  { name:"Premium Jack", type:"sativa", thc_min:19, thc_max:24, cbd:0.1, description:"Premium Jack is an elite phenotype of Jack Herer with enhanced resin production and a sharper, spicier terpene profile. It retains the classic Jack Herer experience — clear-headed creativity, energy, and focus — but turned up a notch.", effects:["Energetic","Creative","Focused","Uplifted","Euphoric"], terpenes:["Terpinolene","Myrcene","Ocimene"], flavors:["Pine","Earthy","Spicy","Woody","Citrus"], tags:["daytime","sativa-dom","creative","focus","potent"], rating:4.6 },

  // ── GELATO / SHERBET ─────────────────────────────────────────────────────────
  { name:"Gelato 33", type:"hybrid", thc_min:20, thc_max:27, cbd:0.1, description:"Gelato 33, also known as 'Larry Bird,' is perhaps the most iconic Gelato cut. This balanced hybrid smells of dessert and berries with a smooth, sweet flavor and a powerful, full-body euphoria that keeps the mind lucid. A modern benchmark strain.", effects:["Euphoric","Relaxed","Happy","Creative","Uplifted"], terpenes:["Caryophyllene","Limonene","Myrcene"], flavors:["Sweet","Berry","Citrus","Earthy","Floral"], tags:["hybrid","potent","evening","dessert","legendary"], rating:4.8 },
  { name:"Gelato 41", type:"hybrid", thc_min:20, thc_max:27, cbd:0.1, description:"Gelato 41, or 'Bacio,' is one of the top Gelato cuts from the Cookies Family. Known for enormous trichome coverage, its aroma is intensely sweet with berry and earthy undertones. The effect is a powerful, euphoric, body-relaxing high.", effects:["Euphoric","Relaxed","Happy","Uplifted","Sedated"], terpenes:["Caryophyllene","Myrcene","Limonene"], flavors:["Sweet","Berry","Earthy","Cookie","Mint"], tags:["hybrid","potent","nighttime","dessert","modern"], rating:4.7 },
  { name:"Gelato 45", type:"hybrid", thc_min:20, thc_max:27, cbd:0.1, description:"Gelato 45 is a premium Gelato phenotype prized for its creamy, dessert flavor and well-rounded high. Its terpene profile delivers a sweet, minty-berry aroma and the effect is simultaneously relaxing and mentally uplifting.", effects:["Euphoric","Relaxed","Happy","Creative","Uplifted"], terpenes:["Limonene","Caryophyllene","Linalool"], flavors:["Sweet","Mint","Berry","Cream","Earthy"], tags:["hybrid","potent","evening","dessert","modern"], rating:4.6 },
  { name:"Bacio Gelato", type:"hybrid", thc_min:21, thc_max:28, cbd:0.1, description:"Bacio is Gelato 41's other name and is among the most decorated Gelato cuts. Its name means 'kiss' in Italian, fitting for a strain this smooth and sweet. Dense, trichome-packed buds deliver a rich, creamy berry taste and a heavy euphoric high.", effects:["Euphoric","Relaxed","Sedated","Happy","Uplifted"], terpenes:["Caryophyllene","Myrcene","Limonene"], flavors:["Berry","Sweet","Cream","Earthy","Minty"], tags:["hybrid","potent","nighttime","dessert","exotic"], rating:4.8 },
  { name:"Dolato", type:"hybrid", thc_min:20, thc_max:27, cbd:0.1, description:"Dolato is a cross of Do-Si-Dos and Gelato 41, combining two of the most potent strains on the market. The result is a deeply relaxing, euphoric hybrid with a sweet, cookie-berry aroma and exceptionally heavy resin production.", effects:["Euphoric","Relaxed","Sleepy","Happy","Sedated"], terpenes:["Caryophyllene","Limonene","Myrcene"], flavors:["Sweet","Berry","Cookie","Earthy","Mint"], tags:["nighttime","potent","hybrid","dessert","exotic"], rating:4.7 },
  { name:"Gelato Cake", type:"hybrid", thc_min:22, thc_max:28, cbd:0.1, description:"Gelato Cake is a cross of Gelato 33 and Wedding Cake — two modern legends in one. Its aroma is a rich blend of sweet cream, vanilla, and berries. The high is intensely euphoric and relaxing, with serious couch-lock potential.", effects:["Euphoric","Relaxed","Sedated","Happy","Sleepy"], terpenes:["Caryophyllene","Limonene","Myrcene"], flavors:["Sweet","Vanilla","Berry","Cream","Earthy"], tags:["nighttime","potent","hybrid","dessert","modern"], rating:4.7 },
  { name:"Sherbet OG", type:"hybrid", thc_min:18, thc_max:24, cbd:0.1, description:"Sherbet OG (or Pink Panties × Sunset Sherbet) delivers a fruity, creamy sweetness backed by OG Kush earthiness. The effect is a euphoric, relaxed, and sociable high that's perfect for unwinding without full sedation.", effects:["Relaxed","Euphoric","Happy","Uplifted","Sleepy"], terpenes:["Caryophyllene","Myrcene","Limonene"], flavors:["Sweet","Berry","Cream","Earthy","Citrus"], tags:["evening","hybrid","dessert","relaxing","social"], rating:4.5 },
  { name:"Mango Sherbet", type:"hybrid", thc_min:17, thc_max:22, cbd:0.1, description:"Mango Sherbet is a tropical, fruity hybrid that tastes as vibrant as it sounds. Ripe mango meets the creamy sweetness of Sherbet genetics for a strain that's both delicious and gently euphoric. Great for relaxed daytime use.", effects:["Happy","Relaxed","Uplifted","Euphoric","Creative"], terpenes:["Myrcene","Limonene","Ocimene"], flavors:["Mango","Tropical","Sweet","Cream","Fruity"], tags:["daytime","hybrid","fruity","tropical","beginner-friendly"], rating:4.3 },
  { name:"Orange Sherbet", type:"hybrid", thc_min:17, thc_max:22, cbd:0.1, description:"Orange Sherbet delivers a burst of fresh citrus and creamy sweetness reminiscent of an orange creamsicle. Its effect is uplifting and happy with a gentle body relaxation — a perfect daytime treat for mood elevation.", effects:["Happy","Uplifted","Relaxed","Euphoric","Creative"], terpenes:["Limonene","Myrcene","Terpinolene"], flavors:["Orange","Citrus","Sweet","Cream","Tropical"], tags:["daytime","hybrid","citrus","sweet","social"], rating:4.3 },
  { name:"Raspberry Sherbet", type:"hybrid", thc_min:17, thc_max:21, cbd:0.1, description:"Raspberry Sherbet is a fruity, sweet hybrid with a bright raspberry aroma and creamy undertones. Its effect is gently euphoric and relaxing — uplifting enough for daytime but smooth enough for evenings.", effects:["Happy","Relaxed","Uplifted","Euphoric","Giggly"], terpenes:["Myrcene","Linalool","Limonene"], flavors:["Raspberry","Sweet","Berry","Cream","Floral"], tags:["hybrid","daytime","fruity","sweet","beginner-friendly"], rating:4.2 },
  { name:"Peach Sherbet", type:"hybrid", thc_min:16, thc_max:21, cbd:0.1, description:"Peach Sherbet captures the essence of a ripe, juicy peach with cream and sweet citrus undertones. This pleasant hybrid delivers a happy, balanced high that's great for social settings or relaxed creative activities.", effects:["Happy","Uplifted","Relaxed","Creative","Euphoric"], terpenes:["Myrcene","Limonene","Linalool"], flavors:["Peach","Sweet","Cream","Fruity","Citrus"], tags:["hybrid","daytime","fruity","social","sweet"], rating:4.2 },

  // ── RUNTZ / ZKITTLEZ FAMILY ──────────────────────────────────────────────────
  { name:"Tropical Runtz", type:"hybrid", thc_min:19, thc_max:25, cbd:0.1, description:"Tropical Runtz takes the candy-sweet Runtz base and pushes it into exotic, tropical fruit territory. Think mango, papaya, and passionfruit layered over sweet candy on the exhale. The effect is euphoric, uplifting, and relaxing.", effects:["Euphoric","Happy","Relaxed","Uplifted","Creative"], terpenes:["Limonene","Myrcene","Ocimene"], flavors:["Tropical","Mango","Sweet","Candy","Fruity"], tags:["hybrid","daytime","fruity","tropical","social"], rating:4.4 },
  { name:"Watermelon Runtz", type:"hybrid", thc_min:19, thc_max:25, cbd:0.1, description:"Watermelon Runtz smells like a watermelon Jolly Rancher — sweet, fresh, and irresistible. This Runtz phenotype delivers the classic Runtz euphoria with a distinctly fruity, watermelon-candy twist.", effects:["Euphoric","Happy","Relaxed","Uplifted","Giggly"], terpenes:["Myrcene","Limonene","Linalool"], flavors:["Watermelon","Sweet","Candy","Fruity","Berry"], tags:["hybrid","daytime","fruity","sweet","social"], rating:4.4 },
  { name:"Rainbow Runtz", type:"hybrid", thc_min:20, thc_max:26, cbd:0.1, description:"Rainbow Runtz is a vibrant, multi-layered Runtz phenotype with a complex candy-fruit aroma that shifts as you smell it. Its effect is powerfully euphoric and relaxing — a genuinely happy strain that lives up to its colorful name.", effects:["Euphoric","Happy","Relaxed","Uplifted","Creative"], terpenes:["Limonene","Caryophyllene","Myrcene"], flavors:["Sweet","Candy","Fruity","Berry","Tropical"], tags:["hybrid","potent","social","sweet","modern"], rating:4.5 },
  { name:"Banana Runtz", type:"hybrid", thc_min:20, thc_max:25, cbd:0.1, description:"Banana Runtz combines Runtz's candy sweetness with Banana's tropical, creamy notes. The aroma is ripe banana and sweet cream candy — distinctively dessert-like. The effect is a euphoric, relaxing hybrid high.", effects:["Euphoric","Happy","Relaxed","Uplifted","Sleepy"], terpenes:["Myrcene","Limonene","Linalool"], flavors:["Banana","Sweet","Cream","Candy","Tropical"], tags:["hybrid","evening","fruity","sweet","dessert"], rating:4.4 },
  { name:"Purple Runtz", type:"hybrid", thc_min:19, thc_max:24, cbd:0.1, description:"Purple Runtz brings the classic candy-sweet Runtz profile together with deep grape and berry notes. The buds are often purple-hued, the aroma is fruity-sweet candy, and the effect is a balanced, euphoric relaxation.", effects:["Relaxed","Euphoric","Happy","Uplifted","Sleepy"], terpenes:["Myrcene","Caryophyllene","Linalool"], flavors:["Grape","Berry","Sweet","Candy","Earthy"], tags:["hybrid","evening","fruity","sweet","relaxing"], rating:4.4 },
  { name:"Grape Runtz", type:"hybrid", thc_min:19, thc_max:24, cbd:0.1, description:"Grape Runtz is a phenotype that emphasizes the grape and berry side of Runtz genetics. Deep, sweet grape candy aroma with earthy undertones and a relaxed, happy euphoric effect.", effects:["Happy","Relaxed","Euphoric","Uplifted","Creative"], terpenes:["Myrcene","Linalool","Limonene"], flavors:["Grape","Sweet","Berry","Candy","Earthy"], tags:["hybrid","evening","fruity","sweet","relaxing"], rating:4.3 },
  { name:"Peach Runtz", type:"hybrid", thc_min:19, thc_max:24, cbd:0.1, description:"Peach Runtz is a delicious Runtz phenotype with a peachy, sweet-candy aroma that makes it instantly appealing. The high is uplifting and euphoric with a mellow body relaxation — great for afternoon use.", effects:["Happy","Uplifted","Relaxed","Euphoric","Giggly"], terpenes:["Limonene","Myrcene","Linalool"], flavors:["Peach","Sweet","Candy","Fruity","Cream"], tags:["hybrid","daytime","fruity","sweet","social"], rating:4.3 },
  { name:"Runtz OG", type:"hybrid", thc_min:19, thc_max:26, cbd:0.1, description:"Runtz OG takes the Runtz candy profile and grounds it with OG Kush's earthy, piney depth. The result is a more complex, robust Runtz experience with the same euphoric, relaxing effect but with added depth of flavor.", effects:["Euphoric","Relaxed","Happy","Uplifted","Creative"], terpenes:["Caryophyllene","Limonene","Myrcene"], flavors:["Sweet","Candy","Earthy","Pine","Citrus"], tags:["hybrid","potent","evening","og","dessert"], rating:4.5 },
  { name:"Grape Zkittlez", type:"hybrid", thc_min:17, thc_max:23, cbd:0.1, description:"Grape Zkittlez pushes Zkittlez genetics toward deep grape and berry territory. Dense, fragrant buds deliver a candy-grape aroma with an uplifting, relaxed effect that mirrors the taste of grape candy.", effects:["Relaxed","Happy","Euphoric","Uplifted","Hungry"], terpenes:["Myrcene","Linalool","Caryophyllene"], flavors:["Grape","Berry","Sweet","Candy","Earthy"], tags:["hybrid","evening","fruity","sweet","relaxing"], rating:4.3 },
  { name:"Melon Zkittlez", type:"hybrid", thc_min:16, thc_max:22, cbd:0.1, description:"Melon Zkittlez expresses the tropical, melon side of the Zkittlez family. Sweet, juicy watermelon and honeydew aromas with earthy undertones. Effect is calming, happy, and mellow.", effects:["Happy","Relaxed","Uplifted","Euphoric","Giggly"], terpenes:["Myrcene","Limonene","Terpinolene"], flavors:["Melon","Watermelon","Sweet","Tropical","Earthy"], tags:["hybrid","daytime","fruity","tropical","beginner-friendly"], rating:4.2 },
  { name:"Rainbow Belts", type:"hybrid", thc_min:20, thc_max:27, cbd:0.1, description:"Rainbow Belts (Zkittlez × Moonbow) is a stunningly fruity hybrid with a candy-sweet aroma reminiscent of rainbow belt candy. Exceptionally terpy buds produce a balanced, euphoric high with strong body relaxation.", effects:["Euphoric","Relaxed","Happy","Uplifted","Creative"], terpenes:["Limonene","Myrcene","Caryophyllene"], flavors:["Sweet","Candy","Fruity","Tropical","Berry"], tags:["hybrid","potent","evening","exotic","modern"], rating:4.7 },

  // ── CAKE / WEDDING CAKE VARIANTS ────────────────────────────────────────────
  { name:"Wedding Pie", type:"hybrid", thc_min:20, thc_max:26, cbd:0.1, description:"Wedding Pie is a cross of Wedding Cake and Grape Pie that results in a gloriously sweet, tangy strain. Its aroma blends wedding cake vanilla with grape candy for an irresistible combination. The effect is deeply relaxing and euphoric.", effects:["Relaxed","Euphoric","Happy","Sleepy","Uplifted"], terpenes:["Caryophyllene","Myrcene","Limonene"], flavors:["Sweet","Vanilla","Grape","Berry","Earthy"], tags:["hybrid","nighttime","dessert","relaxing","modern"], rating:4.5 },
  { name:"Triangle Mints", type:"hybrid", thc_min:22, thc_max:28, cbd:0.1, description:"Triangle Mints (Triangle Kush × Animal Mints) is a terpene powerhouse with a complex minty, earthy, and fuel-forward aroma. This heavy hybrid delivers intense euphoria followed by serious body sedation — reserve for experienced users.", effects:["Euphoric","Sedated","Relaxed","Happy","Sleepy"], terpenes:["Caryophyllene","Limonene","Myrcene"], flavors:["Mint","Earthy","Fuel","Cookie","Spicy"], tags:["nighttime","potent","hybrid","sedating","exotic"], rating:4.6 },
  { name:"Cherry Cake", type:"hybrid", thc_min:19, thc_max:25, cbd:0.1, description:"Cherry Cake is a mouthwatering hybrid with a sweet cherry dessert aroma backed by vanilla and earth. A perfect evening strain that delivers pleasant euphoria and body relaxation with a flavor that sticks with you.", effects:["Happy","Relaxed","Euphoric","Uplifted","Sleepy"], terpenes:["Myrcene","Linalool","Caryophyllene"], flavors:["Cherry","Sweet","Vanilla","Berry","Earthy"], tags:["hybrid","evening","fruity","dessert","relaxing"], rating:4.4 },
  { name:"Blueberry Cake", type:"hybrid", thc_min:18, thc_max:24, cbd:0.1, description:"Blueberry Cake combines the sweet berry genetics of Blueberry with the rich dessert profile of Wedding Cake. The result is a sweet, berry-forward hybrid that delivers euphoric relaxation and a mouthwatering flavor.", effects:["Relaxed","Happy","Euphoric","Uplifted","Sleepy"], terpenes:["Myrcene","Linalool","Caryophyllene"], flavors:["Blueberry","Berry","Sweet","Vanilla","Earthy"], tags:["hybrid","evening","fruity","dessert","relaxing"], rating:4.3 },
  { name:"Cake Pop", type:"hybrid", thc_min:20, thc_max:25, cbd:0.1, description:"Cake Pop is a Seed Junky creation crossing Wedding Cake and Lemon Bean. Its aroma is sweet lemon cake with earthy undertones, and the effect is a balanced, euphoric high with full-body relaxation.", effects:["Euphoric","Relaxed","Happy","Uplifted","Creative"], terpenes:["Limonene","Caryophyllene","Myrcene"], flavors:["Lemon","Sweet","Cake","Vanilla","Earthy"], tags:["hybrid","evening","dessert","citrus","modern"], rating:4.5 },

  // ── MODERN EXOTICS ───────────────────────────────────────────────────────────
  { name:"Oreoz", type:"hybrid", thc_min:22, thc_max:33, cbd:0.1, description:"Oreoz (Oreo Cookies × Secret Weapon) is one of the most potent modern hybrids, routinely testing over 30% THC. Its aroma is of dark chocolate, cookie, and diesel with a rich, dessert-like flavor. The high is intensely euphoric, creative, and physically sedating.", effects:["Euphoric","Relaxed","Creative","Happy","Sedated"], terpenes:["Caryophyllene","Limonene","Myrcene"], flavors:["Chocolate","Cookie","Sweet","Diesel","Earthy"], tags:["hybrid","potent","nighttime","dessert","modern"], rating:4.7 },
  { name:"Zoap", type:"hybrid", thc_min:22, thc_max:28, cbd:0.1, description:"Zoap (Rainbow Belts × Zkittlez) is a vibrant, aromatic hybrid with an extraordinary tropical candy aroma and stunning bag appeal. Its effect is euphoric and uplifting, settling into a comfortable body relaxation — a top-shelf modern exotic.", effects:["Euphoric","Happy","Relaxed","Uplifted","Creative"], terpenes:["Limonene","Caryophyllene","Myrcene"], flavors:["Tropical","Candy","Sweet","Fruity","Earthy"], tags:["hybrid","potent","daytime","exotic","modern"], rating:4.7 },
  { name:"Apples and Bananas", type:"hybrid", thc_min:24, thc_max:32, cbd:0.1, description:"Apples and Bananas is a Compound Genetics masterpiece combining Platinum Cookies × Granddaddy Purple × Blue Power × Gelatti. Extremely potent and uniquely aromatic, it smells exactly as its name suggests — fresh apples and ripe bananas. A collector's strain.", effects:["Euphoric","Relaxed","Sedated","Happy","Creative"], terpenes:["Limonene","Caryophyllene","Myrcene"], flavors:["Apple","Banana","Sweet","Tropical","Earthy"], tags:["hybrid","potent","nighttime","exotic","collector"], rating:4.7 },
  { name:"Ice Cream Man", type:"hybrid", thc_min:21, thc_max:28, cbd:0.1, description:"Ice Cream Man (Legends OG × Jet Fuel Gelato) is a dessert-forward hybrid with a creamy, vanilla ice cream aroma and a fuel undercurrent. The high is full-body euphoric relaxation with a dreamy, uplifting mental state.", effects:["Euphoric","Relaxed","Happy","Creative","Uplifted"], terpenes:["Limonene","Caryophyllene","Myrcene"], flavors:["Vanilla","Cream","Sweet","Fuel","Earthy"], tags:["hybrid","potent","evening","dessert","modern"], rating:4.6 },
  { name:"Jokerz", type:"hybrid", thc_min:22, thc_max:28, cbd:0.1, description:"Jokerz is a Compound Genetics strain (White Runtz × Jet Fuel Gelato) with a candy-sweet, fruity aroma and serious potency. Its euphoric, mentally stimulating high transitions into deep body relaxation — a strain that keeps you guessing.", effects:["Euphoric","Happy","Relaxed","Creative","Uplifted"], terpenes:["Caryophyllene","Limonene","Myrcene"], flavors:["Sweet","Candy","Fruity","Fuel","Earthy"], tags:["hybrid","potent","evening","exotic","modern"], rating:4.6 },
  { name:"Grapes and Cream", type:"hybrid", thc_min:20, thc_max:27, cbd:0.1, description:"Grapes and Cream is a luscious indica-dominant hybrid with a rich grape candy and cream aroma. Its smooth, sweet flavor leads into a deeply relaxing, euphoric body high that's perfect for unwinding.", effects:["Relaxed","Euphoric","Happy","Sleepy","Uplifted"], terpenes:["Myrcene","Linalool","Caryophyllene"], flavors:["Grape","Cream","Sweet","Berry","Vanilla"], tags:["hybrid","nighttime","fruity","dessert","relaxing"], rating:4.5 },
  { name:"Grape Cream Cake", type:"hybrid", thc_min:20, thc_max:26, cbd:0.1, description:"Grape Cream Cake combines Grape Pie, Wedding Cake, and Koolato genetics for a dessert lover's dream. Its aroma is rich grape candy with sweet cream and vanilla, and the effect is a deep, sedating euphoria.", effects:["Euphoric","Relaxed","Sleepy","Happy","Sedated"], terpenes:["Caryophyllene","Myrcene","Linalool"], flavors:["Grape","Cream","Vanilla","Sweet","Berry"], tags:["nighttime","hybrid","dessert","fruity","sedating"], rating:4.5 },
  { name:"Frozen Grapes", type:"hybrid", thc_min:19, thc_max:25, cbd:0.1, description:"Frozen Grapes is a frosty, terpene-rich hybrid with a distinct grape and sweet berry aroma. Its name references both its flavor and its extraordinary trichome coverage. The effect is euphoric and gently sedating.", effects:["Relaxed","Euphoric","Happy","Uplifted","Sleepy"], terpenes:["Myrcene","Linalool","Caryophyllene"], flavors:["Grape","Berry","Sweet","Earthy","Floral"], tags:["hybrid","evening","fruity","relaxing","modern"], rating:4.4 },
  { name:"Grape Gasoline", type:"hybrid", thc_min:20, thc_max:26, cbd:0.1, description:"Grape Gasoline is a head-turning combination of deep grape sweetness and sharp fuel/diesel notes. This unusual pairing creates a complex aroma and a powerful, fast-hitting euphoric high with indica body weight.", effects:["Euphoric","Relaxed","Happy","Creative","Uplifted"], terpenes:["Caryophyllene","Myrcene","Limonene"], flavors:["Grape","Diesel","Fuel","Sweet","Berry"], tags:["hybrid","potent","evening","pungent","exotic"], rating:4.4 },
  { name:"Lemon Cherry Cookies", type:"hybrid", thc_min:20, thc_max:26, cbd:0.1, description:"Lemon Cherry Cookies layers the bright citrus of lemon with sweet cherry and cookie undertones. A tangy-sweet, complex aroma leads into a euphoric, happy, and relaxed high — the kind of strain that disappears from dispensary shelves fast.", effects:["Euphoric","Happy","Relaxed","Uplifted","Creative"], terpenes:["Limonene","Caryophyllene","Linalool"], flavors:["Lemon","Cherry","Cookie","Sweet","Citrus"], tags:["hybrid","daytime","citrus","sweet","modern"], rating:4.5 },
  { name:"Purple Lemonade", type:"hybrid", thc_min:18, thc_max:23, cbd:0.1, description:"Purple Lemonade is a visually stunning hybrid with deep purple hues and a tart, citrus-lemonade aroma. Its effect is uplifting and creative, with a euphoric social buzz and gentle body relaxation.", effects:["Happy","Uplifted","Euphoric","Creative","Relaxed"], terpenes:["Limonene","Myrcene","Linalool"], flavors:["Lemon","Citrus","Berry","Sweet","Grape"], tags:["hybrid","daytime","citrus","fruity","social"], rating:4.3 },
  { name:"Runtz Muffin", type:"hybrid", thc_min:20, thc_max:28, cbd:0.1, description:"Runtz Muffin is an Barneys Farm cross with an incredible baked goods aroma — think blueberry muffin meets candy. Potent and flavorful, it delivers a long-lasting euphoric high with strong body relaxation.", effects:["Euphoric","Relaxed","Happy","Creative","Sleepy"], terpenes:["Myrcene","Limonene","Caryophyllene"], flavors:["Sweet","Blueberry","Muffin","Berry","Candy"], tags:["hybrid","potent","evening","dessert","fruity"], rating:4.6 },
  { name:"Super Boof", type:"hybrid", thc_min:22, thc_max:30, cbd:0.1, description:"Super Boof (Black Cherry Gelato × Tropicana Cookies) is a powerhouse modern hybrid with exceptional flavor and potency. Its aroma is cherry, tropical fruit, and cookies — and the high is intensely euphoric, creative, and physically relaxing.", effects:["Euphoric","Creative","Relaxed","Happy","Uplifted"], terpenes:["Limonene","Caryophyllene","Myrcene"], flavors:["Cherry","Tropical","Cookie","Sweet","Citrus"], tags:["hybrid","potent","daytime","exotic","modern"], rating:4.7 },
  { name:"Gastro Pop", type:"hybrid", thc_min:22, thc_max:28, cbd:0.1, description:"Gastro Pop (Apples and Bananas × Grape Gas) is an Airfield Supply Company × Compound Genetics collaboration with a complex, layered fruity aroma — think tropical fruit punch. Extremely potent and terpy, it delivers a euphoric, body-relaxing high.", effects:["Euphoric","Relaxed","Happy","Creative","Sedated"], terpenes:["Limonene","Caryophyllene","Myrcene"], flavors:["Tropical","Fruity","Grape","Sweet","Earthy"], tags:["hybrid","potent","evening","exotic","modern"], rating:4.7 },

  // ── CBD / MEDICAL ────────────────────────────────────────────────────────────
  { name:"Ringo's Gift", type:"hybrid", thc_min:7, thc_max:15, cbd:15.0, description:"Ringo's Gift is named after Lawrence Ringo, one of the pioneers of high-CBD cannabis breeding. It has an exceptional CBD:THC ratio, delivering gentle, clear-headed relaxation with potent anti-anxiety and anti-inflammatory effects without intoxication.", effects:["Relaxed","Focused","Uplifted","Happy","Clear-headed"], terpenes:["Myrcene","Caryophyllene","Pinene"], flavors:["Earthy","Woody","Herbal","Pine"], tags:["medical","cbd","daytime","anxiety","pain-relief"], rating:4.5 },
  { name:"Harle-Tsu", type:"hybrid", thc_min:1, thc_max:7, cbd:18.0, description:"Harle-Tsu is a cross of Harlequin and Sour Tsunami with one of the highest CBD:THC ratios available. Virtually non-intoxicating, it provides powerful anti-inflammatory and anxiolytic effects perfect for daytime medical use.", effects:["Relaxed","Focused","Clear-headed","Uplifted","Happy"], terpenes:["Myrcene","Caryophyllene","Pinene"], flavors:["Earthy","Woody","Herbal","Sweet"], tags:["medical","cbd","daytime","non-intoxicating","pain-relief"], rating:4.5 },
  { name:"Sour Tsunami", type:"hybrid", thc_min:5, thc_max:13, cbd:11.0, description:"Sour Tsunami was one of the first strains specifically bred for high CBD. Created by Lawrence Ringo, it delivers significant therapeutic benefit with mild psychoactive effects — great for pain, inflammation, and anxiety management.", effects:["Relaxed","Focused","Clear-headed","Happy","Uplifted"], terpenes:["Myrcene","Pinene","Caryophyllene"], flavors:["Earthy","Diesel","Herbal","Sweet"], tags:["medical","cbd","daytime","pioneer","pain-relief"], rating:4.4 },
  { name:"Stephen Hawking Kush", type:"indica", thc_min:5, thc_max:13, cbd:13.0, description:"Stephen Hawking Kush is a high-CBD indica strain with a gentle, calming effect. Named in honor of the physicist, it combines the therapeutic benefits of CBD with mild indica relaxation — excellent for pain, spasms, and sleep.", effects:["Relaxed","Sleepy","Happy","Clear-headed","Sedated"], terpenes:["Myrcene","Linalool","Caryophyllene"], flavors:["Earthy","Sweet","Herbal","Berry"], tags:["medical","cbd","nighttime","pain-relief","sleep"], rating:4.4 },
  { name:"Valentine X", type:"indica", thc_min:1, thc_max:8, cbd:25.0, description:"Valentine X is an extremely high-CBD strain named for Saint Valentine, patron saint of epilepsy. With a CBD:THC ratio often exceeding 25:1, it provides powerful neurological and anti-inflammatory benefits with virtually no psychoactive effect.", effects:["Relaxed","Clear-headed","Focused","Happy","Uplifted"], terpenes:["Myrcene","Caryophyllene","Pinene"], flavors:["Earthy","Herbal","Woody","Pine"], tags:["medical","cbd","daytime","epilepsy","non-intoxicating"], rating:4.5 },

  // ── INDICA CLASSICS ──────────────────────────────────────────────────────────
  { name:"Sensi Star", type:"indica", thc_min:18, thc_max:24, cbd:0.1, description:"Sensi Star is a multiple Cannabis Cup winner from Paradise Seeds. This pure indica is renowned for its potency, stunning resin coverage, and deeply relaxing, almost narcotic body high with sweet, earthy flavors.", effects:["Relaxed","Sleepy","Euphoric","Sedated","Happy"], terpenes:["Myrcene","Linalool","Caryophyllene"], flavors:["Earthy","Sweet","Pine","Woody","Herbal"], tags:["nighttime","indica-dom","potent","award-winning","medical"], rating:4.6 },
  { name:"Shishkaberry", type:"indica", thc_min:17, thc_max:22, cbd:0.1, description:"Shishkaberry (DJ Short Blueberry × Afghani) is a BC-bred indica with a spectacular blueberry-fruit aroma and a deeply relaxing, sedating effect. Its berries-and-earth flavor is exceptional and the high is long-lasting.", effects:["Relaxed","Sleepy","Euphoric","Happy","Sedated"], terpenes:["Myrcene","Linalool","Caryophyllene"], flavors:["Blueberry","Berry","Earthy","Sweet","Fruity"], tags:["nighttime","indica-dom","fruity","medical","award-winning"], rating:4.5 },
  { name:"Sweet Tooth", type:"indica", thc_min:16, thc_max:21, cbd:0.2, description:"Sweet Tooth is a BC Seeds creation that won the High Times Cannabis Cup in 2001. This indica-dominant strain has a uniquely sweet, candy-like aroma and produces a mellow, happy high that's relaxing without heavy sedation.", effects:["Relaxed","Happy","Euphoric","Uplifted","Sleepy"], terpenes:["Myrcene","Linalool","Limonene"], flavors:["Sweet","Floral","Candy","Berry","Earthy"], tags:["evening","indica-dom","sweet","medical","award-winning"], rating:4.4 },
  { name:"Mendo Purps", type:"indica", thc_min:18, thc_max:24, cbd:0.1, description:"Mendo Purps comes from the legendary Mendocino County cannabis region of Northern California. This purple, aromatic indica delivers a relaxing, euphoric high with a complex grape and berry aroma — a California classic.", effects:["Relaxed","Euphoric","Happy","Sleepy","Uplifted"], terpenes:["Myrcene","Linalool","Caryophyllene"], flavors:["Grape","Berry","Earthy","Sweet","Floral"], tags:["nighttime","indica-dom","california","classic","fruity"], rating:4.4 },
  { name:"Querkle", type:"indica", thc_min:16, thc_max:22, cbd:0.1, description:"Querkle (Purple Urkle × Space Queen) is a stunning purple indica with dense, grape-colored buds and a rich berry-grape aroma. Its effect is deeply sedating and euphoric — a nighttime indica for serious relaxation.", effects:["Relaxed","Sleepy","Euphoric","Sedated","Happy"], terpenes:["Myrcene","Linalool","Caryophyllene"], flavors:["Grape","Berry","Earthy","Sweet","Purple"], tags:["nighttime","indica-dom","fruity","sedating","rare"], rating:4.4 },
  { name:"Space Queen", type:"hybrid", thc_min:17, thc_max:22, cbd:0.1, description:"Space Queen (Romulan × Cinderella 99) is a hard-hitting hybrid from BC's Subcool Seeds. Its sweet, fruity aroma of cherry and vanilla is backed by an intensely euphoric, energetic, and creative high — a true head-stash strain.", effects:["Euphoric","Creative","Energetic","Happy","Uplifted"], terpenes:["Terpinolene","Myrcene","Caryophyllene"], flavors:["Cherry","Vanilla","Sweet","Fruity","Earthy"], tags:["daytime","hybrid","fruity","creative","rare"], rating:4.5 },
  { name:"Snow White", type:"hybrid", thc_min:18, thc_max:23, cbd:0.1, description:"Snow White is a White Widow phenotype known for heavy resin production and a clear, euphoric high. Its appearance lives up to the name — pure white trichomes covering dense buds. The effect is uplifting and sociable.", effects:["Happy","Uplifted","Euphoric","Creative","Relaxed"], terpenes:["Myrcene","Caryophyllene","Pinene"], flavors:["Earthy","Pine","Woody","Sweet","Spicy"], tags:["hybrid","daytime","resinous","social","classic"], rating:4.4 },

  // ── SATIVA CLASSICS ──────────────────────────────────────────────────────────
  { name:"XJ-13", type:"hybrid", thc_min:17, thc_max:22, cbd:0.1, description:"XJ-13 is a Jack Herer × G13 Haze cross with an exceptionally citrus-forward aroma and balanced, uplifting effect. This California classic delivers creative focus and uplifted mood without anxiety — a perfect functional sativa.", effects:["Happy","Energetic","Uplifted","Creative","Focused"], terpenes:["Terpinolene","Limonene","Myrcene"], flavors:["Citrus","Lemon","Pine","Earthy","Sweet"], tags:["daytime","hybrid","creative","focus","citrus"], rating:4.5 },
  { name:"Island Sweet Skunk", type:"sativa", thc_min:16, thc_max:22, cbd:0.1, description:"Island Sweet Skunk (ISS) is a beloved Canadian sativa with a tropical, sweet-skunky aroma and a bright, energetic effect. Great for daytime use, socializing, and outdoor activities — it brings out the smiles.", effects:["Happy","Energetic","Uplifted","Creative","Giggly"], terpenes:["Terpinolene","Myrcene","Limonene"], flavors:["Sweet","Tropical","Skunk","Earthy","Citrus"], tags:["daytime","sativa-dom","social","fruity","canadian"], rating:4.4 },
  { name:"The White", type:"hybrid", thc_min:20, thc_max:28, cbd:0.1, description:"The White is one of the most resin-covered strains in existence — buds are so coated in trichomes they appear white. Interestingly, it has almost no detectable aroma. Its effect is a powerfully balanced hybrid high, and it's used extensively as a breeding tool.", effects:["Euphoric","Relaxed","Happy","Creative","Uplifted"], terpenes:["Myrcene","Caryophyllene","Limonene"], flavors:["Earthy","Mild","Floral","Pine","Sweet"], tags:["hybrid","potent","breeding","unique","collector"], rating:4.6 },
  { name:"C99", type:"sativa", thc_min:16, thc_max:22, cbd:0.1, description:"Cinderella 99, also known as C99 or Cindy, is a Brothers Grimm classic with a sweet pineapple-mango aroma and an intensely cerebral, euphoric effect. Fast-acting and thought-provoking, it's a legendary sativa head-stash strain.", effects:["Euphoric","Energetic","Creative","Uplifted","Focused"], terpenes:["Terpinolene","Myrcene","Ocimene"], flavors:["Pineapple","Mango","Sweet","Tropical","Citrus"], tags:["daytime","sativa-dom","fruity","creative","legendary"], rating:4.6 },

  // ── SKUNK FAMILY ─────────────────────────────────────────────────────────────
  { name:"Super Skunk", type:"indica", thc_min:17, thc_max:22, cbd:0.2, description:"Super Skunk is a Skunk #1 × Afghani cross from Sensi Seeds that amplifies the classic skunky aroma and adds indica body weight. A dependable, classic strain with a strong, pungent smell and a relaxing, happy effect.", effects:["Relaxed","Happy","Euphoric","Uplifted","Hungry"], terpenes:["Myrcene","Caryophyllene","Limonene"], flavors:["Skunk","Earthy","Sweet","Pungent","Herbal"], tags:["evening","indica-dom","classic","pungent","beginner-friendly"], rating:4.3 },
  { name:"Skunk Berry", type:"hybrid", thc_min:17, thc_max:22, cbd:0.1, description:"Skunk Berry blends the pungent skunkiness of Skunk genetics with sweet, berry-forward flavors. An unusual and pleasant combination that delivers a euphoric, relaxed hybrid effect.", effects:["Happy","Relaxed","Euphoric","Uplifted","Creative"], terpenes:["Myrcene","Linalool","Limonene"], flavors:["Berry","Skunk","Sweet","Earthy","Fruity"], tags:["hybrid","evening","fruity","pungent","relaxing"], rating:4.2 },

  // ── BERRY / BLUEBERRY FAMILY ─────────────────────────────────────────────────
  { name:"Blueberry Headband", type:"hybrid", thc_min:18, thc_max:23, cbd:0.1, description:"Blueberry Headband combines the sweet blueberry notes of Blueberry with the potent Headband genetics. Users report the classic headband pressure with a sweet berry aroma and a balanced, long-lasting euphoric effect.", effects:["Euphoric","Relaxed","Happy","Uplifted","Creative"], terpenes:["Myrcene","Limonene","Linalool"], flavors:["Blueberry","Berry","Earthy","Sweet","Pine"], tags:["hybrid","evening","fruity","potent","relaxing"], rating:4.4 },
  { name:"Blueberry OG", type:"hybrid", thc_min:18, thc_max:24, cbd:0.1, description:"Blueberry OG merges the sweet berry genetics of Blueberry with OG Kush's earthy, piney depth. The result is a deeply relaxing hybrid with a gorgeous blueberry and earth aroma and a euphoric, heavy body effect.", effects:["Relaxed","Euphoric","Happy","Sleepy","Uplifted"], terpenes:["Myrcene","Linalool","Caryophyllene"], flavors:["Blueberry","Berry","Earthy","Pine","Sweet"], tags:["hybrid","nighttime","fruity","og","relaxing"], rating:4.4 },
  { name:"Cherry Berry", type:"hybrid", thc_min:16, thc_max:21, cbd:0.1, description:"Cherry Berry is a flavorful hybrid with a sweet cherry and mixed berry aroma that's hard to resist. Its effect is gently euphoric and relaxing — a pleasant, easy-going strain for evenings.", effects:["Happy","Relaxed","Uplifted","Euphoric","Giggly"], terpenes:["Myrcene","Linalool","Limonene"], flavors:["Cherry","Berry","Sweet","Fruity","Earthy"], tags:["hybrid","evening","fruity","sweet","relaxing"], rating:4.2 },
  { name:"Blackberry OG", type:"hybrid", thc_min:18, thc_max:24, cbd:0.1, description:"Blackberry OG combines Blackberry Kush genetics with classic OG for a strain with deep berry sweetness backed by earthy, piney OG character. Its effect is relaxing and euphoric — a classic evening hybrid.", effects:["Relaxed","Euphoric","Happy","Sleepy","Uplifted"], terpenes:["Myrcene","Linalool","Caryophyllene"], flavors:["Blackberry","Berry","Earthy","Pine","Sweet"], tags:["hybrid","nighttime","fruity","og","relaxing"], rating:4.3 },

  // ── TROPICAL / PAPAYA ────────────────────────────────────────────────────────
  { name:"Papaya Cake", type:"hybrid", thc_min:19, thc_max:25, cbd:0.1, description:"Papaya Cake (Papaya × Wedding Cake) is a tropical dessert hybrid with a juicy papaya and sweet vanilla aroma. Dense, resinous buds deliver a euphoric, deeply relaxing effect — a vacation in a joint.", effects:["Relaxed","Euphoric","Happy","Uplifted","Sleepy"], terpenes:["Myrcene","Caryophyllene","Limonene"], flavors:["Papaya","Tropical","Sweet","Vanilla","Earthy"], tags:["hybrid","nighttime","tropical","dessert","modern"], rating:4.5 },
  { name:"Papaya Punch", type:"hybrid", thc_min:18, thc_max:24, cbd:0.1, description:"Papaya Punch (Papaya × Purple Punch) is a tropical indica-leaning hybrid with stunning purple hues and a fruity papaya-grape aroma. Its effect is relaxing and euphoric with smooth body sedation.", effects:["Relaxed","Euphoric","Happy","Sleepy","Uplifted"], terpenes:["Myrcene","Linalool","Caryophyllene"], flavors:["Papaya","Tropical","Grape","Sweet","Berry"], tags:["hybrid","nighttime","tropical","fruity","relaxing"], rating:4.4 },
  { name:"Pineapple Kush", type:"hybrid", thc_min:17, thc_max:21, cbd:0.2, description:"Pineapple Kush blends the tropical sweetness of Pineapple Express with classic kush relaxation. The result is a smooth, sweet-tasting hybrid that's great for daytime use — uplifting without overwhelming.", effects:["Happy","Relaxed","Uplifted","Euphoric","Creative"], terpenes:["Myrcene","Limonene","Linalool"], flavors:["Pineapple","Tropical","Sweet","Earthy","Citrus"], tags:["hybrid","daytime","tropical","sweet","beginner-friendly"], rating:4.3 },
  { name:"Guava Cake", type:"hybrid", thc_min:20, thc_max:26, cbd:0.1, description:"Guava Cake is a Seed Junky Genetics creation that blends exotic guava tropicality with Wedding Cake's sweet creaminess. Extraordinary terpene expression — it smells exactly like fresh guava. Effect is euphoric and deeply relaxing.", effects:["Euphoric","Relaxed","Happy","Uplifted","Creative"], terpenes:["Myrcene","Limonene","Caryophyllene"], flavors:["Guava","Tropical","Sweet","Cream","Fruity"], tags:["hybrid","potent","evening","exotic","tropical"], rating:4.6 },
  { name:"Mango Tango", type:"hybrid", thc_min:17, thc_max:22, cbd:0.1, description:"Mango Tango is a tropical sativa-leaning hybrid with an overwhelmingly mango-citrus aroma. Its effect is energetic, creative, and uplifting — perfect for a tropical mindset and outdoor activities.", effects:["Happy","Energetic","Uplifted","Creative","Euphoric"], terpenes:["Myrcene","Limonene","Terpinolene"], flavors:["Mango","Tropical","Citrus","Sweet","Fruity"], tags:["daytime","hybrid","tropical","fruity","social"], rating:4.3 },
  { name:"Peach OG", type:"hybrid", thc_min:18, thc_max:24, cbd:0.1, description:"Peach OG combines ripe peach sweetness with OG Kush's earthy, piney backbone. This pleasant hybrid delivers a sweet, fruity aroma and a balanced effect — uplifting euphoria settling into gentle body relaxation.", effects:["Happy","Relaxed","Euphoric","Uplifted","Creative"], terpenes:["Myrcene","Limonene","Caryophyllene"], flavors:["Peach","Sweet","Earthy","Citrus","Pine"], tags:["hybrid","daytime","fruity","og","relaxing"], rating:4.3 },

  // ── NEWER POTENT STRAINS ─────────────────────────────────────────────────────
  { name:"Gushers OG", type:"hybrid", thc_min:20, thc_max:27, cbd:0.1, description:"Gushers OG (Gelato 41 × Triangle Kush) is one of the more popular Cookie Family strains, delivering a tropical fruit candy aroma and a powerfully euphoric, body-heavy effect. Named for the fruity candy — and it delivers.", effects:["Euphoric","Relaxed","Happy","Sedated","Uplifted"], terpenes:["Caryophyllene","Limonene","Myrcene"], flavors:["Tropical","Sweet","Candy","Grape","Earthy"], tags:["hybrid","potent","nighttime","dessert","modern"], rating:4.6 },
  { name:"Jet Fuel", type:"hybrid", thc_min:19, thc_max:26, cbd:0.1, description:"Jet Fuel (also called G6) is a Aspen OG × High Country Diesel cross with a sharp, diesel-forward aroma and rocket-fuel energy. The effect hits hard and fast — euphoric, energizing, and mentally clear with little body sedation.", effects:["Energetic","Euphoric","Focused","Creative","Uplifted"], terpenes:["Terpinolene","Limonene","Caryophyllene"], flavors:["Diesel","Fuel","Earthy","Pine","Sour"], tags:["daytime","sativa-dom","potent","focus","diesel"], rating:4.5 },
  { name:"Garlic Breath", type:"hybrid", thc_min:21, thc_max:28, cbd:0.1, description:"Garlic Breath (Chemdog D × Motor Breath) is intentionally pungent — its garlic, fuel, and earth aroma is an acquired taste. But the effect is exceptional: deep, full-body relaxation with a powerful, euphoric mental high.", effects:["Relaxed","Euphoric","Sedated","Happy","Sleepy"], terpenes:["Caryophyllene","Myrcene","Limonene"], flavors:["Garlic","Earthy","Diesel","Fuel","Pungent"], tags:["nighttime","potent","hybrid","pungent","sedating"], rating:4.4 },
  { name:"Biscotti Cake", type:"hybrid", thc_min:21, thc_max:28, cbd:0.1, description:"Biscotti Cake combines the nutty, sweet Biscotti genetics with Wedding Cake's vanilla richness. An extraordinarily flavorful dessert strain with a powerful euphoric and relaxing effect — one of the finest hybrids for flavor lovers.", effects:["Euphoric","Relaxed","Happy","Creative","Uplifted"], terpenes:["Caryophyllene","Limonene","Myrcene"], flavors:["Sweet","Vanilla","Nutty","Cookie","Earthy"], tags:["hybrid","evening","dessert","potent","modern"], rating:4.6 },
  { name:"Kush Mintz", type:"hybrid", thc_min:22, thc_max:28, cbd:0.1, description:"Kush Mintz (Animal Mints × Bubba Kush) is an incredibly potent hybrid with a distinctive minty, earthy aroma with cool fuel notes. The high is intensely relaxing and euphoric — a creeping, long-lasting stone.", effects:["Relaxed","Euphoric","Sedated","Happy","Sleepy"], terpenes:["Caryophyllene","Myrcene","Limonene"], flavors:["Mint","Earthy","Kush","Cookie","Sweet"], tags:["nighttime","potent","hybrid","sedating","modern"], rating:4.7 },
  { name:"London Pound Cake 75", type:"hybrid", thc_min:22, thc_max:29, cbd:0.1, description:"London Pound Cake 75 is the 75-day phenotype of LPC, selected for maximum terpene expression and density. Its grape, lemon, and berry-cake aroma is extraordinary. The effect is a deeply euphoric and sedating indica-leaning high.", effects:["Euphoric","Relaxed","Sedated","Happy","Sleepy"], terpenes:["Caryophyllene","Myrcene","Limonene"], flavors:["Grape","Lemon","Berry","Sweet","Vanilla"], tags:["nighttime","potent","hybrid","exotic","dessert"], rating:4.7 },
  { name:"Cereal Milk OG", type:"hybrid", thc_min:21, thc_max:27, cbd:0.1, description:"Cereal Milk OG merges the creamy, sweet Cereal Milk genetics with classic OG depth. The result is a complex, dessert-forward hybrid with a sweet cream and earthy OG aroma — grounding and euphoric in equal measure.", effects:["Euphoric","Relaxed","Happy","Creative","Uplifted"], terpenes:["Caryophyllene","Limonene","Myrcene"], flavors:["Cream","Sweet","Earthy","Cookie","Vanilla"], tags:["hybrid","evening","dessert","og","potent"], rating:4.5 },
  { name:"Motorbreath 15", type:"indica", thc_min:22, thc_max:28, cbd:0.1, description:"Motorbreath 15 is a legendary cut of the Motorbreath line (Chemdog × SFV OG Kush) with an intense diesel and earthy aroma. This powerful indica delivers a sedating, heavy body high with deep euphoria — a true gas-station strain.", effects:["Relaxed","Sedated","Euphoric","Sleepy","Happy"], terpenes:["Myrcene","Caryophyllene","Limonene"], flavors:["Diesel","Earthy","Fuel","Pine","Pungent"], tags:["nighttime","potent","indica-dom","sedating","diesel"], rating:4.6 },
  { name:"Peanut Butter Gelato", type:"hybrid", thc_min:21, thc_max:27, cbd:0.1, description:"Peanut Butter Gelato combines nutty Peanut Butter Breath with creamy Gelato genetics for a rich, dessert experience. Its aroma is unmistakably nutty and sweet, and the effect is a deeply relaxing, euphoric full-body high.", effects:["Relaxed","Euphoric","Happy","Sleepy","Uplifted"], terpenes:["Caryophyllene","Myrcene","Limonene"], flavors:["Peanut Butter","Nutty","Sweet","Cream","Earthy"], tags:["hybrid","nighttime","dessert","potent","modern"], rating:4.5 },

  // ── HEIRLOOM / UNIQUE ────────────────────────────────────────────────────────
  { name:"Blue Mystic", type:"indica", thc_min:16, thc_max:21, cbd:0.1, description:"Blue Mystic is a Dutch-bred indica cross of Blueberry and an unknown strain. Its sweet blueberry aroma is soft and pleasant, and the effect is a calm, relaxing body high that doesn't overwhelm — perfect for beginner indica users.", effects:["Relaxed","Happy","Euphoric","Sleepy","Uplifted"], terpenes:["Myrcene","Linalool","Limonene"], flavors:["Blueberry","Sweet","Berry","Earthy","Floral"], tags:["nighttime","indica-dom","fruity","beginner-friendly","relaxing"], rating:4.2 },
  { name:"Jet Fuel Gelato", type:"hybrid", thc_min:21, thc_max:28, cbd:0.1, description:"Jet Fuel Gelato (High Octane OG × Gelato 45) is a fuel-meets-dessert masterpiece. The sharp diesel aroma blends with sweet gelato undertones in an unexpected but harmonious way. The effect is fast, euphoric, and deeply relaxing.", effects:["Euphoric","Relaxed","Creative","Happy","Uplifted"], terpenes:["Caryophyllene","Limonene","Myrcene"], flavors:["Diesel","Sweet","Fuel","Cream","Earthy"], tags:["hybrid","potent","evening","diesel","dessert"], rating:4.6 },
  { name:"GMO Garlic Cookies", type:"hybrid", thc_min:22, thc_max:30, cbd:0.1, description:"GMO (Garlic, Mushroom, Onion Cookies) is one of the most pungent strains ever bred. Despite the unusual savory aroma — garlic, coffee, and diesel — the effect is exceptionally potent, deeply euphoric, and sedating. A cult classic.", effects:["Euphoric","Sedated","Relaxed","Happy","Sleepy"], terpenes:["Caryophyllene","Myrcene","Limonene"], flavors:["Garlic","Diesel","Earthy","Coffee","Pungent"], tags:["nighttime","potent","hybrid","pungent","cult-classic"], rating:4.7 },
  { name:"Garlic Cocktail", type:"hybrid", thc_min:22, thc_max:28, cbd:0.1, description:"Garlic Cocktail is a powerful hybrid with a complex, savory-meets-sweet aroma — garlic and fuel with fruity undertones. A divisive but rewarding strain, its effect is deeply euphoric and relaxing.", effects:["Euphoric","Relaxed","Happy","Sedated","Creative"], terpenes:["Caryophyllene","Myrcene","Limonene"], flavors:["Garlic","Earthy","Diesel","Sweet","Pungent"], tags:["hybrid","potent","nighttime","pungent","exotic"], rating:4.4 },
  { name:"Romulan Grapefruit", type:"hybrid", thc_min:17, thc_max:22, cbd:0.1, description:"Romulan Grapefruit takes the heavy indica Romulan and brightens it with Grapefruit's citrusy, uplifting qualities. The result is a well-balanced hybrid with a tangy citrus aroma and both body relaxation and mental uplift.", effects:["Relaxed","Happy","Euphoric","Uplifted","Creative"], terpenes:["Limonene","Myrcene","Terpinolene"], flavors:["Grapefruit","Citrus","Earthy","Pine","Sweet"], tags:["hybrid","daytime","citrus","relaxing","balanced"], rating:4.3 },
  { name:"Alien Bubba", type:"indica", thc_min:18, thc_max:24, cbd:0.1, description:"Alien Bubba (Alien Kush × Bubba Kush) is a powerhouse indica cross with a deeply earthy, kushy aroma and an almost narcotic body effect. Dense, sticky buds and serious potency make this a go-to for insomnia and pain.", effects:["Relaxed","Sleepy","Sedated","Euphoric","Happy"], terpenes:["Myrcene","Caryophyllene","Linalool"], flavors:["Earthy","Kush","Pine","Woody","Sweet"], tags:["nighttime","indica-dom","potent","sedating","medical"], rating:4.4 },
  { name:"Dosidos 22", type:"indica", thc_min:22, thc_max:28, cbd:0.1, description:"Dosidos 22 is a sought-after phenotype of Do-Si-Dos, selected for exceptional potency and a minty, lime, and earthy aroma. Its effect is a heavy, long-lasting body stone with euphoric mental overtones.", effects:["Relaxed","Euphoric","Sedated","Happy","Sleepy"], terpenes:["Caryophyllene","Limonene","Myrcene"], flavors:["Lime","Mint","Earthy","Sweet","Cookie"], tags:["nighttime","potent","indica-dom","sedating","modern"], rating:4.6 },
];

const toAdd = NEW_STRAINS.filter(s => !existingNames.has(s.name.toLowerCase()));
console.log(`Adding ${toAdd.length} new strains (${existing.length} existing → ${existing.length + toAdd.length} total)`);

const combined = [...existing, ...toAdd];
fs.writeFileSync(STRAINS_PATH, JSON.stringify(combined, null, 2));
console.log(`Done! Saved ${combined.length} strains to strains.json`);
